import { IProject } from '@shared/models/project.model';

export const allProjectsContent: IProject[] = [
  {
    image: '/assets/images/projects/main/js-game-thumbnail.jpg',
    technologies: ['JavaScript'],
    title: 'Arcade game in JS',
    link: 'https://shadowdrake21.github.io/js-game/',
    githubLink: 'https://github.com/ShadowDrake21/js-game',
    year: '2023',
  },
  {
    image: '/assets/images/projects/main/book-angular-app-thumbnail.jpg',
    technologies: ['Angular', 'Firebase'],
    title: 'Book Angular application',
    link: 'https://book-angular-app.netlify.app/',
    githubLink: 'https://github.com/ShadowDrake21/book-angular-app',
    year: '2024',
  },
  {
    image: '/assets/images/projects/main/dictionary-rxjs-thumbnail.jpg',
    technologies: ['Angular', 'RxJS', 'Firebase'],
    title: 'Dictionary translator with RxJS',
    link: 'https://dictionary-rxjs.netlify.app/',
    githubLink: 'https://github.com/ShadowDrake21/dictionary-translator',
    year: '2024',
  },
  {
    image: '/assets/images/projects/main/weather-app-thumbnail.jpg',
    technologies: ['Angular', 'RxJS', 'Angular Material', 'NodeJS'],
    title: 'Weather application with RxJS',
    link: 'https://rxjs-weather-app.netlify.app/',
    githubLink: 'https://github.com/ShadowDrake21/weather-app',
    year: '2024',
  },
  {
    image: '/assets/images/projects/main/ngrx-shop-thumbnail.jpg',
    technologies: [
      'Angular',
      'NgRX',
      'RxJS',
      'Firebase',
      'Stripe',
      'Bootstrap 5',
      'NodeJS',
    ],
    title: 'E-shpp with NgRX an RxJS',
    link: 'https://ngrx-internet-shop.netlify.app/',
    githubLink: 'https://github.com/ShadowDrake21/ngrx-internet-shop',
    year: '2024',
  },
  {
    image: '/assets/images/projects/main/portfolio-thumbnail.jpg',
    technologies: ['Angular', 'RxJS'],
    title: 'My portfolio',
    link: '',
    githubLink: 'https://github.com/ShadowDrake21/my-portfolio',
    year: '2024',
  },
];
