import { IProject } from '@shared/models/project.model';

export const mainStackProjectsContent: IProject[] = [
  {
    image: '/assets/images/projects/main/js-game-thumbnail.jpg',
    technologies: ['JavaScript'],
    title: 'Arcade game in JS',
    link: 'https://shadowdrake21.github.io/js-game/',
    githubLink: 'https://github.com/ShadowDrake21/js-game',
    year: '2023',
  },
  {
    image: '/assets/images/projects/main/book-angular-app-thumbnail.jpg',
    technologies: ['Angular', 'Firebase', 'TailwindCSS'],
    title: 'Book Angular application',
    link: 'https://book-angular-app.netlify.app/',
    githubLink: 'https://github.com/ShadowDrake21/book-angular-app',
    year: '2024',
  },
  {
    image: '/assets/images/projects/main/dictionary-rxjs-thumbnail.jpg',
    technologies: ['Angular', 'RxJS', 'Firebase'],
    title: 'Dictionary translator with RxJS',
    link: 'https://dictionary-rxjs.netlify.app/',
    githubLink: 'https://github.com/ShadowDrake21/dictionary-translator',
    year: '2024',
  },
  {
    image: '/assets/images/projects/main/weather-app-thumbnail.jpg',
    technologies: ['Angular', 'RxJS', 'Angular Material', 'NodeJS'],
    title: 'Weather application with RxJS',
    link: 'https://rxjs-weather-app.netlify.app/',
    githubLink: 'https://github.com/ShadowDrake21/weather-app',
    year: '2024',
  },
  {
    image: '/assets/images/projects/main/ngrx-shop-thumbnail.jpg',
    technologies: [
      'Angular',
      'NgRX',
      'RxJS',
      'Firebase',
      'Stripe',
      'Bootstrap 5',
      'NodeJS',
    ],
    title: 'E-shop with NgRX an RxJS',
    link: 'https://ngrx-internet-shop.netlify.app/',
    githubLink: 'https://github.com/ShadowDrake21/ngrx-internet-shop',
    year: '2024',
  },
  {
    image: '/assets/images/projects/main/portfolio-thumbnail.jpg',
    technologies: ['Angular', 'RxJS', 'NgRX', 'Angular Material'],
    title: 'My portfolio',
    link: 'https://drake21-portfolio.netlify.app/',
    githubLink: 'https://github.com/ShadowDrake21/my-portfolio',
    year: '2024',
  },
  {
    image: '/assets/images/projects/main/genius-js-application.jpg',
    technologies: ['JavaScript'],
    title: 'Genius music plication in JS',
    link: 'https://drake21-music-documentation-app.netlify.app/',
    githubLink: 'https://github.com/ShadowDrake21/genius-js-application',
    year: '2024',
  },
  {
    image: '/assets/images/projects/main/typescripti-task-management-app.jpg',
    technologies: ['TypeScript', 'Firebase'],
    title: 'TypeScript Task management app',
    link: 'https://drake21-ts-task-management-app.netlify.app/',
    githubLink:
      'https://github.com/ShadowDrake21/typescript-task-management-app',
    year: '2024',
  },
  {
    image: '/assets/images/projects/main/ng-signals-pexels-app.jpg',
    technologies: ['Angular', 'RxJS', 'Angular Material', 'Firebase'],
    title: 'Pexels application with Angular Signals',
    link: 'https://drake21-signals-pexels-app.netlify.app/',
    githubLink: 'https://github.com/ShadowDrake21/ng-signals-pexels-app',
    year: '2024',
  },
  {
    image: '/assets/images/projects/main/onpush-ssr-app.jpg',
    technologies: ['Angular', 'RxJS', 'TailwindCSS'],
    title: 'OnPush SSR Application',
    link: 'https://drake21-onpush-ssr-app.netlify.app/',
    githubLink: 'https://github.com/ShadowDrake21/onpush-ssr-app',
    year: '2024',
  },
  {
    image: '/assets/images/projects/main/ng-maps-thumbnail.jpg',
    technologies: ['Angular', 'RxJS', 'Angular Material', 'Firebase'],
    title: 'Ng Maps Application with Google Maps',
    link: 'https://drake21-maps-app.netlify.app/',
    githubLink: 'https://github.com/ShadowDrake21/ng-maps-app',
    year: '2024',
  },
];

export const otherProjectsContent: IProject[] = [
  {
    image: '/assets/images/projects/other/tutor app.jpg',
    technologies: ['React', 'TailwindCSS'],
    title: 'Tutor site',
    link: 'https://tutor-site-theta.vercel.app/',
    githubLink: 'https://github.com/ShadowDrake21/tutor-site',
    year: '2023',
  },
  {
    image: '/assets/images/projects/other/marvel app.jpg',
    technologies: ['React'],
    title: 'Marvel app',
    link: 'https://aesthetic-empanada-6857b1.netlify.app/',
    githubLink: 'https://github.com/ShadowDrake21/marvel-app',
    year: '2023',
  },
  {
    image: '/assets/images/projects/other/bmw app.jpg',
    technologies: ['React'],
    title: 'BMW app',
    link: 'https://krapyvianskyi-drake21-bmw-app.netlify.app/i5',
    githubLink: 'https://github.com/ShadowDrake21/bmw-app',
    year: '2023',
  },
];
