[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist/portfolio"
  command = 'mkdir -p src/environments && echo -e "export const environment = {};" > src/environments/environment.ts && echo -e "export const environment = {};" > src/environments/environment.development.ts && npm run build'
